# Generated by Django 5.1 on 2024-09-10 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 10, 10, 2, 3, 590203, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 10, 10, 2, 26, 539745, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
